### ISSUE TITLE
PagedPublicationFragment NullPointerException

### ISSUE THREAD

**Issue by VitaliyShuba** [tjek/tjek-android-sdk#41]
While using `PagedPublicationFragment` I can reproduce a crash.

Steps to reproduce:
1) Tap on the product - so `HotspotOverlay` animation appears
2) Swipe to the next page fast before animation end - then app crashes

`java.lang.NullPointerException: null cannot be cast to non-null type com.tjek.sdk.publicationviewer.paged.layouts.PublicationSpreadLayout
        at v30.f.onAnimationEnd(HotspotOverlay.kt:34)
        at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:7134)
        at android.view.View.draw(View.java:22613)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4528)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4313)
        at android.view.View.updateDisplayListIfDirty(View.java:21570)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
        at android.view.View.updateDisplayListIfDirty(View.java:21535)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
        at android.view.View.updateDisplayListIfDirty(View.java:21535)
        ......`

This probably happens in `HotspotOverlay.kt` in `onAnimationEnd` where you have not safe cast 
`parent as PublicationSpreadLayout`.

The easiest way is to use safe cast here `parent ?as PublicationSpreadLayout`.

**Comment by AgneseBussone** [comment]
Thanks for reporting!
I'll fix it ASAP.

**Comment by HenrikBacher** [comment]
@AgneseBussone can you provide an update on this issue?

**Comment by AgneseBussone** [comment]
Sorry about the delay. I'll try to look into it today or tomorrow so I can release a patch by this week.

**Comment by AgneseBussone** [comment]
Fixed in `6.0.2`
